// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spvlyhhbhrgbigwwbzhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdmx5aGhiaHJnYmlnd3diemhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MjgzNjEsImV4cCI6MjA4ODQwNDM2MX0.bDJJnjo2-DHojwps8O1vbPwNhiO1zLTYkcDMVrRdn4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});